#!/usr/bin/env bash
# This script is a wrapper for zellij, show a friendly tui interface to deal
# with zellij sessions

# define colors
RED="$(echo -en '\033[0;31m')"
GREEN="$(echo -en '\033[0;32m')"
YELLOW="$(echo -en '\033[0;33m')"
BLUE="$(echo -en '\033[0;34m')"
PURPLE="$(echo -en '\033[0;35m')"
NC="$(echo -en '\033[0m')"

# make sure that dependencies are installed
for package in zellij fzf; do
	command -v "$package" &> /dev/null && continue
	echo -e "${RED}ERROR: $package is not installed!${NC}"
	exit 1
done

# define FZF dracula theme
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
--color=fg:#f8f8f2,bg:#282a36,hl:#bd93f9
--color=fg+:#f8f8f2,bg+:#44475a,hl+:#bd93f9
--color=info:#ffb86c,prompt:#50fa7b,pointer:#ff79c6
--color=marker:#ff79c6,spinner:#ffb86c,header:#6272a4 --ansi --cycle'

# clear the screen
clear

echo -e "${GREEN}Welcome to zellij runner!${NC}\n\n"

options=('attach' 'create' 'list' 'delete')
PS3="${PURPLE}Please enter your choice: ${BLUE}"
echo -en "${BLUE}"
select choice in "${options[@]}"; do
	echo -e "${NC}"

	case "$choice" in
		'attach')
			session_name="$(zellij ls \
				| fzf --cycle --header "Select session to attach" --prompt "Session: " \
				| awk '{print $1}')"
			zellij a "$session_name"
			exit 0 ;;
		'create')
			read -p "${BLUE}Session name ${RED}(Leave empty to abort)${BLUE}: ${YELLOW}" -r session_name
			echo -en "${NC}"
			[ -z "$session_name" ] && continue
			zellij -s "$session_name"
			exit 0 ;;
		'delete') zellij ls | fzf -m --cycle --header "Select sessions to delete" \
			| awk '{print $1}' | xargs -I {} zellij delete-session {} ; exit 0 ;;
		'list') zellij ls | less -SR ;;
	esac
done
